annotations:
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 10.12.1.0/24
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 80.0
    y1: -40.0
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: '.1'
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -40.0
    y1: -40.0
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: '.2'
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 320.0
    y1: -40.0
    z_index: 2
  - border_color: '#808080FF'
    border_style: ''
    color: '#0013FFFF'
    thickness: 1
    type: ellipse
    x1: -80.0
    y1: 0.0
    x2: 80.0
    y2: 120.0
    z_index: 1
  - border_color: '#808080FF'
    border_style: ''
    color: '#123500FF'
    thickness: 1
    type: ellipse
    x1: 360.0
    y1: 0.0
    x2: 80.0
    y2: 120.0
    z_index: 1
  - border_color: '#808080FF'
    border_style: ''
    color: '#FFFFFFFF'
    line_end: null
    line_start: null
    thickness: 1
    type: line
    x1: -40.0
    y1: 0.0
    x2: -160.0
    y2: 160.0
    z_index: 3
  - border_color: '#808080FF'
    border_style: ''
    color: '#FFFFFFFF'
    line_end: null
    line_start: null
    thickness: 1
    type: line
    x1: 400.0
    y1: 160.0
    x2: 280.0
    y2: 0.0
    z_index: 4
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: |-
      Loopback0
      192.168.1.1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -240.0
    y1: 160.0
    z_index: 5
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: |-
      Loopback0
      192.168.2.2
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 400.0
    y1: 160.0
    z_index: 6
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: AS 65100
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -120.0
    y1: -80.0
    z_index: 7
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: AS 65200
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 320.0
    y1: -80.0
    z_index: 8
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: |-
      Default IPv4
      Address-Family
      Enabled
    text_font: monospace
    text_italic: false
    text_size: 10
    text_unit: pt
    thickness: 1
    type: text
    x1: -280.0
    y1: 0.0
    z_index: 9
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: |-
      Default IPv4
      Address-Family
      Disabled
    text_font: monospace
    text_italic: false
    text_size: 10
    text_unit: pt
    thickness: 1
    type: text
    x1: 440.0
    y1: 0.0
    z_index: 10
nodes:
  - boot_disk_size: null
    configuration: hostname inserthostname-here
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: R1
    node_definition: iosv
    ram: null
    tags: []
    x: -40
    y: 0
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: hostname inserthostname-here
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: R2
    node_definition: iosv
    ram: null
    tags: []
    x: 320
    y: 0
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
links:
  - id: l0
    n1: n0
    n2: n1
    i1: i2
    i2: i3
    conditioning: {}
    label: iosv-0-GigabitEthernet0/1<->iosv-1-GigabitEthernet0/2
lab:
  description: |-
    Basic BGP Configuration. On R1 the default IPv4
    address-family is enabled and on R2 the default IPv4
    address-family is disable
  notes: ''
  title: Basic BGP Configuration
  version: 0.2.1
